---
media_player:
  - platform: kodi
    host: !secret kodi_ip
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret kodi_mac
          broadcast_address: !secret wol_broadcast_address

