---
# Setup mariadb as database
recorder:
  purge_keep_days: 7
  purge_interval: 1
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - sun2
      - switch
      - light
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
      - sensor.hacs
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.date_time
    event_types:
      - call_service
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop
      - service_registered
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync
