---
sensor:
  - platform: mqtt
    name: "Température séjour"
    unit_of_measurement: '°C'
    state_topic: 'home/sensor/38/temp'

  - platform: mqtt
    name: "Luminosité séjour"
    unit_of_measurement: 'Lux'
    state_topic: 'home/sensor/39/lux'

  - platform: moon

  - platform: sun2
    monitored_conditions:
      - dawn
      - sunrise
      - solar_noon
      - sunset
      - dusk
      - daylight
      - night
      - elevation
      - max_elevation

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
