---
switch:
  - platform: mqtt
    name: "Sentinelle"
    command_topic: "home/switch/dz_switch_198/power"
    state_topic: "home/switch/dz_switch_198/state"
    payload_on: "On"
    payload_off: "Off"
    state_on: "On"
    state_off: "Off"
    icon: "mdi:shield-key"
    optimistic: true
    retain: true

  - platform: wake_on_lan
    name: celebdil
    mac: F4:4D:30:6A:B8:29
    host: 192.168.1.107
