kind: pipeline
name: default

steps:
  - name: test
    image: homeassistant/amd64-homeassistant
    commands:
      - echo "Preparing ..."
      - cp config/drone_secrets.yaml config/secrets.yaml
      - echo "Testing Home Assistant config ..."
      - hass -c config/ --script check_config
      - echo "Cleaning up ..."
      - rm config/secrets.yaml
