kind: pipeline
name: home-assistant 

steps:
  - name: yaml-linting
    image: python:3
    commands:
      - pip3 install --upgrade pip yamllint
      - yamllint config/

  - name: "HA config check"
    image: homeassistant/amd64-homeassistant
    commands:
      - echo "Preparing ..."
      - cp config/.drone_secrets.yaml config/secrets.yaml
      - echo "Testing Home Assistant config ..."
      - hass -c config/ --script check_config
      - echo "Cleaning up ..."
      - rm config/secrets.yaml

  - name: push-github
    pull: always
    image: appleboy/drone-git-push
    settings:
      branch: master
      author_email: "45527+nagubal@users.noreply.github.com"
      author_name: nagubal
      commit: true
      commit_message: "{{commit.message}}"
      followtags: true
      remote: "git@github.com:nagubal/home-assistant-config.git"
    environment:
      GIT_PUSH_SSH_KEY:
        from_secret: git_push_ssh_key

---

kind: pipeline
name: home-assistant-dev 

steps:
  - name: "HA config check: dev branch"
    image: homeassistant/amd64-homeassistant:dev
    pull: always
    failure: ignore
    commands:
      - echo "Preparing ..."
      - cp config/.drone_secrets.yaml config/secrets.yaml
      - echo "Testing Home Assistant config on dev branch..."
      - hass -c config/ --script check_config
      - echo "Cleaning up ..."
      - rm config/secrets.yaml

---
kind: pipeline
name: Telegram notification
depends_on:
  - home-assistant
steps:
  - name: "Telegram notification"
    image: appleboy/drone-telegram
    secrets: [ telegram-redbeard-token, telegram-chatid ]
    when:
      status: [ success, failure ]
    format: markdown
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.


      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```


      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.


      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```


      🌐 {{ build.link }}
      {{/success}}
