kind: pipeline
name: default

steps:
  - name: test
    image: homeassistant/amd64-homeassistant
    commands:
      #- echo "Downloading here_travel_time component"
      #- wget -O /tmp/here.zip https://github.com/eifinger/here_travel_time/archive/master.zip
      #- unzip /tmp/here.zip 'here_travel_time-master/custom_components/here_travel_time/*' -d /tmp/
      #- cp -R /tmp/here_travel_time-master/custom_components/here_travel_time ./custom_components/
      - hass -c config/ --script check_config
      #- echo "Cleaning up custom components"
      #- rm -rf ./custom_components/here_travel_time
