kind: pipeline
name: Home Assistant 

steps:
  - name: yaml-linting
    image: python:3
    commands:
      - pip3 install --upgrade pip yamllint
      - yamllint config/
  - name: "HA config check"
    image: homeassistant/amd64-homeassistant
    commands:
      - echo "Preparing ..."
      - cp config/drone_secrets.yaml config/secrets.yaml
      - echo "Testing Home Assistant config ..."
      - hass -c config/ --script check_config
      - echo "Cleaning up ..."
      - rm config/secrets.yaml
