---
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    restart: always
    network_mode: host
