---
- platform: mqtt
  name: "Présence séjour"
  state_topic: "home/binary_sensor/dz_binary_36/state"
  payload_off: "Off"
  payload_on: "On"
  device_class: motion

- platform: mqtt
  name: "Garage"
  state_topic: "home/binary_sensor/dz_binary_298/state"
  payload_off: "Off"
  payload_on: "On"
  device_class: garage_door

# ESP32 connected to a garage door reed switch
- platform: mqtt
  name: esp32_garage_state
  state_topic: "esp32_garage/binary_sensor/garage/state"
  device_class: garage_door
  unique_id: esp32_garage_reed_switch

- platform: sun2
  monitored_conditions:
    - elevation
    - elevation: 3
    - elevation:
        above: -6
        name: Above Civil Dawn
