---
- platform: mqtt
  name: "Température séjour"
  unit_of_measurement: '°C'
  state_topic: 'home/sensor/38/temp'

- platform: mqtt
  name: "Luminosité séjour"
  unit_of_measurement: 'Lux'
  state_topic: 'home/sensor/39/lux'
