---
homeassistant:
  name: !secret name
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  customize: !include customize.yaml

  packages: !include_dir_named integrations

automation: !include automations.yaml

