---
person.anthony:
  entity_picture: https://nagubal.fr/anthony.jpg
switch.sentinelle:
  icon: mdi:shield-key
light.lampadaire:
  icon: mdi:floor-lamp
light.cuisine:
  friendly_name: Cuisine
  icon: mdi:ceiling-light
light.sejour:
  icon: mdi:vanity-light
light.palier:
  icon: mdi:ceiling-light
light.lampe_cuisine:
  friendly_name: Cuisine
  icon: mdi:ceiling-light
sensor.capteur_escalier_temperature:
  friendly_name: Escalier
sensor.capteur_palier_temperature:
  friendly_name: Palier
sensor.temperature_sejour:
  friendly_name: Séjour
light.lampe_ile_de_re:
  icon: mdi:lamp
switch.sp111_01_switch:
  friendly_name: Ampli
  icon: mdi:audio-video
switch.sp111_02_switch:
  friendly_name: "Chevet Anthony"
  icon: mdi:lamp
binary_sensor.esp32_garage_state:
  friendly_name: "Garage"
